name: Deploy

on:
    workflow_dispatch:
    push:
        branches:
            - cloudflare

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Deploy
              uses: cloudflare/wrangler-action@v3.3.2
              with:
                apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
