name: Discord Notification on Push

on:
  push:
    branches: [main]

jobs:
  congrats:
    name: congratsbot
    if: ${{ github.repository_owner == 'withastro' }}
    uses: withastro/automation/.github/workflows/congratsbot.yml@main
    with:
      EMOJIS: '🎉,🎊,🧑‍🚀,🥳,🙌,🚀,<:houston_product_hunt:1145760743208263904>,<:notworsethanwhatwehadbefore:1020455379353751573> '
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_CONGRATS }}